name: publish-react

on:
  workflow_dispatch:
  release:
    types: [created]
    paths:
      - "packages/react/**"

jobs:
  publish-npm-registry:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./packages/react

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@mj-studio'

      - name: Install modules
        run: yarn

      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
